# デフォルトの設定
# 項目が指定されていなくてもハードコーティング済み

LogPath: "/tmp/iot_gateway.log"

HttpServer:
  Port: 8080
  BasicAuth:
    User: "someone"
    Password: "somepassword"
  StaticPath:
    # 静的ファイルのサーブ
    # フォルダ名をプレフィクスとしてファイルをサーブ
    - "/tmp" #この場合は http://server.address/tmp/file_in_the_dir.txt

SocketServer:
  Port: 8081

Strategy:
  # デバイスからの生存通知が途切れたと判断する時間
  DeviceCycle: 10 #sec
  # 制御権を与える時間
  ControlCycle: 90 #sec